"""
Zenithsui A/B SLM — Model Export Engine
Exports trained SLM parameters to JSON format consumable by Zenithsui's TypeScript client.
"""

import json
from pathlib import Path
from typing import Optional
from .model import DedicatedABModel

def export_model_to_json(model: DedicatedABModel, output_path: str):
    """Exports model weights, prototypes, and thresholds to JSON for TypeScript engine."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        json.dump(model.to_dict(), f, indent=2)
    print(f"Exported model {model.version} to {output_path}")

def export_model_to_typescript(model: DedicatedABModel, output_path: str):
    """Exports model weights as a pure TypeScript module."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    d = model.to_dict()
    ts_code = f"""/**
 * Autogenerated by Zenithsui A/B SLM Export Engine
 * Model Version: {d['version']}
 * Trained Samples: {d.get('trained_samples_count', 0)}
 */

export interface ABModelConfig {{
  version: string;
  num_features: number;
  prototype_a: number[];
  prototype_b: number[];
  feature_weights: number[];
  weights_a: number[];
  weights_b: number[];
  bias_a: number;
  bias_b: number;
  bias_unknown: number;
  temperature: number;
  min_confidence_threshold: number;
  min_margin_threshold: number;
}}

export const ACTIVE_AB_MODEL_CONFIG: ABModelConfig = {json.dumps(d, indent=2)};
"""
    with open(p, "w", encoding="utf-8") as f:
        f.write(ts_code)
    print(f"Exported model TypeScript module to {output_path}")

export_model_for_ts = export_model_to_json

if __name__ == "__main__":
    from .dataset import get_datasets
    from .train import train_ab_slm
    from .evaluate import evaluate_model, print_evaluation_report

    print("Training baseline A/B SLM for production deployment...")
    data = get_datasets(num_a=240, num_b=240, num_unknown=300, seed=42)
    model = train_ab_slm(data["train"], data["val"], version="letter_ab_slm_v1")

    print("\nEvaluating on held-out test split...")
    metrics = evaluate_model(model, data["test"])
    print_evaluation_report(metrics)

    export_path = "lib/sketch-recognition/letter-ab-model-weights.json"
    export_model_for_ts(model, export_path)
