// ---------------------------------------------------------------------------
// Smart Sketch Recognition — Centralized Registry of Supported Classes
// ---------------------------------------------------------------------------

import type { RecognizedSketchKind, SketchClassMetadata } from "./types"

export const SKETCH_REGISTRY: Record<RecognizedSketchKind, SketchClassMetadata> = {
  // --- GEOMETRY ---
  circle: {
    id: "circle",
    label: "Circle",
    category: "geometry",
    aliases: ["round", "ring", "disc"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  ellipse: {
    id: "ellipse",
    label: "Ellipse",
    category: "geometry",
    aliases: ["oval", "egg"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  rectangle: {
    id: "rectangle",
    label: "Rectangle",
    category: "geometry",
    aliases: ["box", "rect", "square"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  triangle: {
    id: "triangle",
    label: "Triangle",
    category: "geometry",
    aliases: ["delta", "pyramid"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  line: {
    id: "line",
    label: "Line",
    category: "geometry",
    aliases: ["segment", "bar", "stroke"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.88,
    autoConvertAllowed: true,
  },
  arrow: {
    id: "arrow",
    label: "Arrow",
    category: "geometry",
    aliases: ["pointer", "vector"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },

  // --- SYMBOLS ---
  checkmark: {
    id: "checkmark",
    label: "Checkmark",
    category: "symbol",
    aliases: ["tick", "check", "correct", "done"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  x: {
    id: "x",
    label: "Cross / X",
    category: "symbol",
    aliases: ["cross", "cancel", "wrong", "delete"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  plus: {
    id: "plus",
    label: "Plus",
    category: "symbol",
    aliases: ["add", "cross-hair", "positive"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  star: {
    id: "star",
    label: "Star",
    category: "symbol",
    aliases: ["favorite", "sparkle", "pentagram", "asterisk"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.82,
    autoConvertAllowed: true,
  },
  heart: {
    id: "heart",
    label: "Heart",
    category: "symbol",
    aliases: ["love", "like"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.82,
    autoConvertAllowed: true,
  },
  cloud: {
    id: "cloud",
    label: "Cloud",
    category: "symbol",
    aliases: ["cumulus", "weather", "storage"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.82,
    autoConvertAllowed: true,
  },

  // --- OBJECTS ---
  apple: {
    id: "apple",
    label: "Apple",
    category: "object",
    aliases: ["fruit"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  house: {
    id: "house",
    label: "House",
    category: "object",
    aliases: ["home", "building"],
    supportsLocal: true, // Multi-stroke or triangle-on-square
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  lightbulb: {
    id: "lightbulb",
    label: "Lightbulb",
    category: "object",
    aliases: ["idea", "bulb", "lamp"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  phone: {
    id: "phone",
    label: "Phone",
    category: "object",
    aliases: ["mobile", "smartphone", "screen"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  tree: {
    id: "tree",
    label: "Tree",
    category: "object",
    aliases: ["plant", "nature"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  folder: {
    id: "folder",
    label: "Folder",
    category: "object",
    aliases: ["directory", "binder"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  camera: {
    id: "camera",
    label: "Camera",
    category: "object",
    aliases: ["photo"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  lock: {
    id: "lock",
    label: "Lock",
    category: "object",
    aliases: ["padlock", "secure"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  envelope: {
    id: "envelope",
    label: "Envelope",
    category: "object",
    aliases: ["mail", "message", "letter"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  calendar: {
    id: "calendar",
    label: "Calendar",
    category: "object",
    aliases: ["date", "schedule"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  document: {
    id: "document",
    label: "Document",
    category: "object",
    aliases: ["doc", "file", "page"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  minus: {
    id: "minus",
    label: "Minus / Dash",
    category: "symbol",
    aliases: ["dash", "hyphen", "negative", "subtract"],
    supportsLocal: true,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  gear: {
    id: "gear",
    label: "Gear",
    category: "object",
    aliases: ["cog", "settings", "options"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  computer: {
    id: "computer",
    label: "Computer / Laptop",
    category: "object",
    aliases: ["laptop", "pc", "workstation"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  monitor: {
    id: "monitor",
    label: "Monitor / Display",
    category: "object",
    aliases: ["display", "screen", "tv"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  person: {
    id: "person",
    label: "Person / User",
    category: "object",
    aliases: ["user", "avatar", "profile", "human"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  car: {
    id: "car",
    label: "Car / Vehicle",
    category: "object",
    aliases: ["vehicle", "automobile"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  clock: {
    id: "clock",
    label: "Clock / Time",
    category: "object",
    aliases: ["time", "timer", "watch"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  microphone: {
    id: "microphone",
    label: "Microphone / Mic",
    category: "object",
    aliases: ["mic", "audio", "record"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  database: {
    id: "database",
    label: "Database / Storage",
    category: "object",
    aliases: ["db", "cylinder", "sql"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
  server: {
    id: "server",
    label: "Server / Rack",
    category: "object",
    aliases: ["rack", "mainframe", "host"],
    supportsLocal: false,
    supportsAI: true,
    minConfidence: 0.85,
    autoConvertAllowed: true,
  },
}

export function isSupportedSketchKind(kind: string): kind is RecognizedSketchKind {
  return kind in SKETCH_REGISTRY
}

export function getSketchMetadata(kind: RecognizedSketchKind): SketchClassMetadata {
  return SKETCH_REGISTRY[kind]
}

export function getSketchLabel(kind: string, text?: string): string {
  if (kind === "text") return text ? `Text "${text}"` : "Text"
  if (isSupportedSketchKind(kind)) {
    return SKETCH_REGISTRY[kind]?.label || kind
  }
  return kind
}
