// ---------------------------------------------------------------------------
// Specialist Sketch Recognition — Class Definitions & Geometric Priors
// Formal class specifications for all 69 recognition targets in Zenithsui.
// ---------------------------------------------------------------------------

import type { ClassDefinition } from "./types"
import { HARD_NEGATIVES_MAP } from "./hard-negatives-matrix"

// ---------------------------------------------------------------------------
// Letter Definitions A–Z (26 Classes)
// ---------------------------------------------------------------------------
export const LETTER_DEFINITIONS: ClassDefinition[] = [
  {
    id: "letter_A",
    targetClass: "A",
    family: "letter",
    description: "Uppercase Letter A",
    positiveDescription: "Two diagonal converging legs joined at apex with horizontal mid-crossbar",
    hardNegatives: HARD_NEGATIVES_MAP["A"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.35, maxAspectRatio: 1.3, closure: "either" },
  },
  {
    id: "letter_B",
    targetClass: "B",
    family: "letter",
    description: "Uppercase Letter B",
    positiveDescription: "Vertical left stem with two stacked convex right loops",
    hardNegatives: HARD_NEGATIVES_MAP["B"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1, 2], minAspectRatio: 0.35, maxAspectRatio: 1.1, closure: "either" },
  },
  {
    id: "letter_C",
    targetClass: "C",
    family: "letter",
    description: "Uppercase Letter C",
    positiveDescription: "Open circular or elliptical arc with right-facing opening",
    hardNegatives: HARD_NEGATIVES_MAP["C"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.4, maxAspectRatio: 1.4, closure: "must_open" },
  },
  {
    id: "letter_D",
    targetClass: "D",
    family: "letter",
    description: "Uppercase Letter D",
    positiveDescription: "Vertical left stem with a single large right convex loop",
    hardNegatives: HARD_NEGATIVES_MAP["D"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1, 2], minAspectRatio: 0.4, maxAspectRatio: 1.2, closure: "either" },
  },
  {
    id: "letter_E",
    targetClass: "E",
    family: "letter",
    description: "Uppercase Letter E",
    positiveDescription: "Vertical stem with three horizontal right bars (top, middle, bottom)",
    hardNegatives: HARD_NEGATIVES_MAP["E"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2, 4], minAspectRatio: 0.35, maxAspectRatio: 1.2, closure: "must_open" },
  },
  {
    id: "letter_F",
    targetClass: "F",
    family: "letter",
    description: "Uppercase Letter F",
    positiveDescription: "Vertical stem with two horizontal right bars (top and middle)",
    hardNegatives: HARD_NEGATIVES_MAP["F"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.35, maxAspectRatio: 1.2, closure: "must_open" },
  },
  {
    id: "letter_G",
    targetClass: "G",
    family: "letter",
    description: "Uppercase Letter G",
    positiveDescription: "Open circular arc ending in a horizontal inward shelf bar",
    hardNegatives: HARD_NEGATIVES_MAP["G"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.45, maxAspectRatio: 1.3, closure: "must_open" },
  },
  {
    id: "letter_H",
    targetClass: "H",
    family: "letter",
    description: "Uppercase Letter H",
    positiveDescription: "Two parallel vertical stems connected by a horizontal middle crossbar",
    hardNegatives: HARD_NEGATIVES_MAP["H"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.4, maxAspectRatio: 1.3, closure: "must_open" },
  },
  {
    id: "letter_I",
    targetClass: "I",
    family: "letter",
    description: "Uppercase Letter I",
    positiveDescription: "Single straight vertical stroke, optionally with top and bottom serifs",
    hardNegatives: HARD_NEGATIVES_MAP["I"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1], minAspectRatio: 0.05, maxAspectRatio: 0.6, minStraightness: 0.85 },
  },
  {
    id: "letter_J",
    targetClass: "J",
    family: "letter",
    description: "Uppercase Letter J",
    positiveDescription: "Vertical stem turning leftward into an upward bottom hook",
    hardNegatives: HARD_NEGATIVES_MAP["J"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.25, maxAspectRatio: 0.9 },
  },
  {
    id: "letter_K",
    targetClass: "K",
    family: "letter",
    description: "Uppercase Letter K",
    positiveDescription: "Vertical stem met by two angled branches extending up-right and down-right",
    hardNegatives: HARD_NEGATIVES_MAP["K"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.4, maxAspectRatio: 1.2 },
  },
  {
    id: "letter_L",
    targetClass: "L",
    family: "letter",
    description: "Uppercase Letter L",
    positiveDescription: "Vertical stem joining a horizontal baseline extending rightward",
    hardNegatives: HARD_NEGATIVES_MAP["L"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1 },
  },
  {
    id: "letter_M",
    targetClass: "M",
    family: "letter",
    description: "Uppercase Letter M",
    positiveDescription: "Two outer vertical legs with a downward V-valley in the center",
    hardNegatives: HARD_NEGATIVES_MAP["M"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [1, 2], minAspectRatio: 0.55, maxAspectRatio: 1.6 },
  },
  {
    id: "letter_N",
    targetClass: "N",
    family: "letter",
    description: "Uppercase Letter N",
    positiveDescription: "Two parallel vertical stems connected by a single top-left to bottom-right diagonal",
    hardNegatives: HARD_NEGATIVES_MAP["N"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1, 3], minAspectRatio: 0.4, maxAspectRatio: 1.3 },
  },
  {
    id: "letter_O",
    targetClass: "O",
    family: "letter",
    description: "Uppercase Letter O",
    positiveDescription: "Continuous closed circular or elliptical loop",
    hardNegatives: HARD_NEGATIVES_MAP["O"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.5, maxAspectRatio: 1.5, closure: "must_close" },
  },
  {
    id: "letter_P",
    targetClass: "P",
    family: "letter",
    description: "Uppercase Letter P",
    positiveDescription: "Vertical left stem with a single upper right convex loop",
    hardNegatives: HARD_NEGATIVES_MAP["P"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1, 2], minAspectRatio: 0.35, maxAspectRatio: 1.1 },
  },
  {
    id: "letter_Q",
    targetClass: "Q",
    family: "letter",
    description: "Uppercase Letter Q",
    positiveDescription: "Closed circular loop with a short diagonal tail at the bottom-right",
    hardNegatives: HARD_NEGATIVES_MAP["Q"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [2], minAspectRatio: 0.5, maxAspectRatio: 1.5 },
  },
  {
    id: "letter_R",
    targetClass: "R",
    family: "letter",
    description: "Uppercase Letter R",
    positiveDescription: "Vertical stem with upper right loop and a descending right leg",
    hardNegatives: HARD_NEGATIVES_MAP["R"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.4, maxAspectRatio: 1.2 },
  },
  {
    id: "letter_S",
    targetClass: "S",
    family: "letter",
    description: "Uppercase Letter S",
    positiveDescription: "Single smooth serpentine curve reversing direction twice",
    hardNegatives: HARD_NEGATIVES_MAP["S"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1, closure: "must_open" },
  },
  {
    id: "letter_T",
    targetClass: "T",
    family: "letter",
    description: "Uppercase Letter T",
    positiveDescription: "Horizontal top bar with a centered descending vertical stem",
    hardNegatives: HARD_NEGATIVES_MAP["T"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [2], minAspectRatio: 0.4, maxAspectRatio: 1.4 },
  },
  {
    id: "letter_U",
    targetClass: "U",
    family: "letter",
    description: "Uppercase Letter U",
    positiveDescription: "Downward curved trough open at the top with parallel sides",
    hardNegatives: HARD_NEGATIVES_MAP["U"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.2, closure: "must_open" },
  },
  {
    id: "letter_V",
    targetClass: "V",
    family: "letter",
    description: "Uppercase Letter V",
    positiveDescription: "Two straight diagonal strokes meeting at a sharp bottom apex",
    hardNegatives: HARD_NEGATIVES_MAP["V"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.3, closure: "must_open" },
  },
  {
    id: "letter_W",
    targetClass: "W",
    family: "letter",
    description: "Uppercase Letter W",
    positiveDescription: "Double downward V-trough forming four alternating diagonals",
    hardNegatives: HARD_NEGATIVES_MAP["W"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [1, 2], minAspectRatio: 0.6, maxAspectRatio: 1.7 },
  },
  {
    id: "letter_X",
    targetClass: "X",
    family: "letter",
    description: "Uppercase Letter X",
    positiveDescription: "Two diagonal strokes crossing in the center",
    hardNegatives: HARD_NEGATIVES_MAP["X"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [2], minAspectRatio: 0.45, maxAspectRatio: 1.4 },
  },
  {
    id: "letter_Y",
    targetClass: "Y",
    family: "letter",
    description: "Uppercase Letter Y",
    positiveDescription: "Upper V-branch joining a descending centered vertical stem",
    hardNegatives: HARD_NEGATIVES_MAP["Y"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2], minAspectRatio: 0.4, maxAspectRatio: 1.3 },
  },
  {
    id: "letter_Z",
    targetClass: "Z",
    family: "letter",
    description: "Uppercase Letter Z",
    positiveDescription: "Top horizontal bar, diagonal descending to bottom-left, bottom horizontal bar",
    hardNegatives: HARD_NEGATIVES_MAP["Z"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1], minAspectRatio: 0.4, maxAspectRatio: 1.3 },
  },
]

// ---------------------------------------------------------------------------
// Digit Definitions 0–9 (10 Classes)
// ---------------------------------------------------------------------------
export const DIGIT_DEFINITIONS: ClassDefinition[] = [
  {
    id: "digit_0",
    targetClass: "0",
    family: "digit",
    description: "Numeric Digit 0",
    positiveDescription: "Closed oval loop, typically taller and narrower than uppercase O",
    hardNegatives: HARD_NEGATIVES_MAP["0"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1, closure: "must_close" },
  },
  {
    id: "digit_1",
    targetClass: "1",
    family: "digit",
    description: "Numeric Digit 1",
    positiveDescription: "Vertical stroke, optionally with angled top hook/flag",
    hardNegatives: HARD_NEGATIVES_MAP["1"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.05, maxAspectRatio: 0.6, minStraightness: 0.85 },
  },
  {
    id: "digit_2",
    targetClass: "2",
    family: "digit",
    description: "Numeric Digit 2",
    positiveDescription: "Top convex arch descending diagonally leftward into a horizontal baseline",
    hardNegatives: HARD_NEGATIVES_MAP["2"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1 },
  },
  {
    id: "digit_3",
    targetClass: "3",
    family: "digit",
    description: "Numeric Digit 3",
    positiveDescription: "Two stacked convex rightward arcs meeting at a center cusp",
    hardNegatives: HARD_NEGATIVES_MAP["3"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1, closure: "must_open" },
  },
  {
    id: "digit_4",
    targetClass: "4",
    family: "digit",
    description: "Numeric Digit 4",
    positiveDescription: "Descending diagonal/vertical meeting horizontal bar crossed by vertical stem",
    hardNegatives: HARD_NEGATIVES_MAP["4"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [2], minAspectRatio: 0.4, maxAspectRatio: 1.2 },
  },
  {
    id: "digit_5",
    targetClass: "5",
    family: "digit",
    description: "Numeric Digit 5",
    positiveDescription: "Top horizontal bar, short vertical left drop, into bottom round convex loop",
    hardNegatives: HARD_NEGATIVES_MAP["5"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1, 2], minAspectRatio: 0.35, maxAspectRatio: 1.1 },
  },
  {
    id: "digit_6",
    targetClass: "6",
    family: "digit",
    description: "Numeric Digit 6",
    positiveDescription: "Smooth arc descending from top-right into a closed bottom circular loop",
    hardNegatives: HARD_NEGATIVES_MAP["6"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.4, maxAspectRatio: 1.1 },
  },
  {
    id: "digit_7",
    targetClass: "7",
    family: "digit",
    description: "Numeric Digit 7",
    positiveDescription: "Top horizontal bar joining a descending diagonal stroke",
    hardNegatives: HARD_NEGATIVES_MAP["7"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1 },
  },
  {
    id: "digit_8",
    targetClass: "8",
    family: "digit",
    description: "Numeric Digit 8",
    positiveDescription: "Continuous symmetrical figure-8 crossing loop",
    hardNegatives: HARD_NEGATIVES_MAP["8"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.35, maxAspectRatio: 1.1, closure: "must_close" },
  },
  {
    id: "digit_9",
    targetClass: "9",
    family: "digit",
    description: "Numeric Digit 9",
    positiveDescription: "Closed upper round loop with descending vertical or curved right stem",
    hardNegatives: HARD_NEGATIVES_MAP["9"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.4, maxAspectRatio: 1.1 },
  },
]

// ---------------------------------------------------------------------------
// Geometry & Symbol Definitions (15 Classes)
// ---------------------------------------------------------------------------
export const GEOMETRY_DEFINITIONS: ClassDefinition[] = [
  {
    id: "geom_line",
    targetClass: "line",
    family: "geometry",
    description: "Straight Line",
    positiveDescription: "High-straightness stroke with wide or tall single span",
    hardNegatives: HARD_NEGATIVES_MAP["line"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.05, maxAspectRatio: 20, minStraightness: 0.88 },
  },
  {
    id: "geom_rectangle",
    targetClass: "rectangle",
    family: "geometry",
    description: "Rectangle",
    positiveDescription: "Closed four-sided polygon with four roughly 90-degree corners",
    hardNegatives: HARD_NEGATIVES_MAP["rectangle"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [1], minAspectRatio: 0.2, maxAspectRatio: 5.0, closure: "must_close" },
  },
  {
    id: "geom_square",
    targetClass: "square",
    family: "geometry",
    description: "Square",
    positiveDescription: "Equilateral four-sided closed polygon with equal width and height",
    hardNegatives: HARD_NEGATIVES_MAP["square"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [1], minAspectRatio: 0.75, maxAspectRatio: 1.33, closure: "must_close" },
  },
  {
    id: "geom_circle",
    targetClass: "circle",
    family: "geometry",
    description: "Circle",
    positiveDescription: "Isotropic closed loop with high circularity and equal radii",
    hardNegatives: HARD_NEGATIVES_MAP["circle"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.72, maxAspectRatio: 1.38, closure: "must_close", minCircularity: 0.68 },
  },
  {
    id: "geom_ellipse",
    targetClass: "ellipse",
    family: "geometry",
    description: "Ellipse",
    positiveDescription: "Smooth closed oval with distinct major and minor axes",
    hardNegatives: HARD_NEGATIVES_MAP["ellipse"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.25, maxAspectRatio: 4.0, closure: "must_close" },
  },
  {
    id: "geom_triangle",
    targetClass: "triangle",
    family: "geometry",
    description: "Triangle",
    positiveDescription: "Closed three-sided polygon with three prominent corners",
    hardNegatives: HARD_NEGATIVES_MAP["triangle"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1], minAspectRatio: 0.4, maxAspectRatio: 2.5, closure: "must_close" },
  },
  {
    id: "geom_rounded_rectangle",
    targetClass: "rounded_rectangle",
    family: "geometry",
    description: "Rounded Rectangle",
    positiveDescription: "Closed four-sided shape with rounded smoothed corners",
    hardNegatives: HARD_NEGATIVES_MAP["rounded_rectangle"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [1], minAspectRatio: 0.25, maxAspectRatio: 4.0, closure: "must_close" },
  },
  {
    id: "geom_arrow",
    targetClass: "arrow",
    family: "geometry",
    description: "Arrow Connector",
    positiveDescription: "Stem line terminating with an acute arrowhead apex",
    hardNegatives: HARD_NEGATIVES_MAP["arrow"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1, 2], minAspectRatio: 0.1, maxAspectRatio: 10.0 },
  },
  {
    id: "sym_checkmark",
    targetClass: "checkmark",
    family: "symbol",
    description: "Checkmark Symbol",
    positiveDescription: "Asymmetric V-gesture with a short downward left tick and tall right upward sweep",
    hardNegatives: HARD_NEGATIVES_MAP["checkmark"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 0.5, maxAspectRatio: 2.5 },
  },
  {
    id: "sym_x",
    targetClass: "x",
    family: "symbol",
    description: "X Mark / Cross",
    positiveDescription: "Two diagonal strokes intersecting near their midpoints",
    hardNegatives: HARD_NEGATIVES_MAP["x"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [2], minAspectRatio: 0.5, maxAspectRatio: 1.8 },
  },
  {
    id: "sym_plus",
    targetClass: "plus",
    family: "symbol",
    description: "Plus Symbol",
    positiveDescription: "Perpendicular horizontal and vertical strokes intersecting at midpoints",
    hardNegatives: HARD_NEGATIVES_MAP["plus"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [2], minAspectRatio: 0.6, maxAspectRatio: 1.6 },
  },
  {
    id: "sym_minus",
    targetClass: "minus",
    family: "symbol",
    description: "Minus Symbol / Dash",
    positiveDescription: "Single horizontal straight stroke with wide aspect ratio",
    hardNegatives: HARD_NEGATIVES_MAP["minus"],
    priors: { minStrokes: 1, maxStrokes: 1, preferredStrokes: [1], minAspectRatio: 1.8, maxAspectRatio: 15.0, minStraightness: 0.85 },
  },
  {
    id: "sym_star",
    targetClass: "star",
    family: "symbol",
    description: "Five-Point Star",
    positiveDescription: "Multi-pointed radial star gesture with alternating inner and outer vertices",
    hardNegatives: HARD_NEGATIVES_MAP["star"],
    priors: { minStrokes: 1, maxStrokes: 5, preferredStrokes: [1], minAspectRatio: 0.7, maxAspectRatio: 1.4 },
  },
  {
    id: "sym_heart",
    targetClass: "heart",
    family: "symbol",
    description: "Heart Symbol",
    positiveDescription: "Two curved upper lobes joining at a top center cleft, tapering to a bottom apex",
    hardNegatives: HARD_NEGATIVES_MAP["heart"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1], minAspectRatio: 0.6, maxAspectRatio: 1.5, closure: "must_close" },
  },
  {
    id: "sym_cloud",
    targetClass: "cloud",
    family: "symbol",
    description: "Cloud Symbol",
    positiveDescription: "Scalloped circular billowing top arcs over a flat horizontal base",
    hardNegatives: HARD_NEGATIVES_MAP["cloud"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1], minAspectRatio: 0.8, maxAspectRatio: 2.8 },
  },
]

// ---------------------------------------------------------------------------
// Semantic Object Definitions (18 Classes)
// ---------------------------------------------------------------------------
export const OBJECT_DEFINITIONS: ClassDefinition[] = [
  {
    id: "obj_apple",
    targetClass: "apple",
    family: "object",
    description: "Apple Object",
    positiveDescription: "Rounded apple silhouette with top indent, stem, and small leaf",
    hardNegatives: HARD_NEGATIVES_MAP["apple"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.65, maxAspectRatio: 1.4 },
  },
  {
    id: "obj_house",
    targetClass: "house",
    family: "object",
    description: "House / Home Object",
    positiveDescription: "Triangular roof over rectangular base walls with door",
    hardNegatives: HARD_NEGATIVES_MAP["house"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2, 3], minAspectRatio: 0.6, maxAspectRatio: 1.6 },
  },
  {
    id: "obj_tree",
    targetClass: "tree",
    family: "object",
    description: "Tree Object",
    positiveDescription: "Fluffy scalloped canopy supported by a straight vertical trunk",
    hardNegatives: HARD_NEGATIVES_MAP["tree"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.45, maxAspectRatio: 1.3 },
  },
  {
    id: "obj_lightbulb",
    targetClass: "lightbulb",
    family: "object",
    description: "Lightbulb / Idea Object",
    positiveDescription: "Round top bulb tapering into a narrow base with screw thread lines",
    hardNegatives: HARD_NEGATIVES_MAP["lightbulb"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2, 3], minAspectRatio: 0.45, maxAspectRatio: 1.2 },
  },
  {
    id: "obj_phone",
    targetClass: "phone",
    family: "object",
    description: "Mobile Phone Object",
    positiveDescription: "Tall rounded rectangle with top speaker slot and bottom home button",
    hardNegatives: HARD_NEGATIVES_MAP["phone"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.35, maxAspectRatio: 0.85 },
  },
  {
    id: "obj_computer",
    targetClass: "computer",
    family: "object",
    description: "Desktop Computer / Laptop Object",
    positiveDescription: "Horizontal monitor display with stand and base keyboard block",
    hardNegatives: HARD_NEGATIVES_MAP["computer"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2, 3], minAspectRatio: 0.8, maxAspectRatio: 2.2 },
  },
  {
    id: "obj_camera",
    targetClass: "camera",
    family: "object",
    description: "Camera Object",
    positiveDescription: "Rectangular body with circular central lens and top flash bump",
    hardNegatives: HARD_NEGATIVES_MAP["camera"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.7, maxAspectRatio: 1.8 },
  },
  {
    id: "obj_folder",
    targetClass: "folder",
    family: "object",
    description: "Directory Folder Object",
    positiveDescription: "Folder shape with a top-left tab protruding above the main body",
    hardNegatives: HARD_NEGATIVES_MAP["folder"],
    priors: { minStrokes: 1, maxStrokes: 2, preferredStrokes: [1, 2], minAspectRatio: 0.8, maxAspectRatio: 2.0 },
  },
  {
    id: "obj_document",
    targetClass: "document",
    family: "object",
    description: "Document / Page Object",
    positiveDescription: "Vertical page rectangle with top-right folded dog-ear corner",
    hardNegatives: HARD_NEGATIVES_MAP["document"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [1, 2], minAspectRatio: 0.45, maxAspectRatio: 0.95 },
  },
  {
    id: "obj_envelope",
    targetClass: "envelope",
    family: "object",
    description: "Mail Envelope Object",
    positiveDescription: "Horizontal rectangle with inner V-fold flap",
    hardNegatives: HARD_NEGATIVES_MAP["envelope"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2], minAspectRatio: 0.9, maxAspectRatio: 2.2 },
  },
  {
    id: "obj_lock",
    targetClass: "lock",
    family: "object",
    description: "Security Padlock Object",
    positiveDescription: "Rectangular or square base body with semicircular shackle loop on top",
    hardNegatives: HARD_NEGATIVES_MAP["lock"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2], minAspectRatio: 0.55, maxAspectRatio: 1.2 },
  },
  {
    id: "obj_calendar",
    targetClass: "calendar",
    family: "object",
    description: "Calendar Schedule Object",
    positiveDescription: "Rectangular card with top hanging ring loops and inner grid lines",
    hardNegatives: HARD_NEGATIVES_MAP["calendar"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2, 3], minAspectRatio: 0.7, maxAspectRatio: 1.5 },
  },
  {
    id: "obj_gear",
    targetClass: "gear",
    family: "object",
    description: "Settings Gear / Cog Object",
    positiveDescription: "Central circular hub surrounded by outer cog teeth",
    hardNegatives: HARD_NEGATIVES_MAP["gear"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2], minAspectRatio: 0.75, maxAspectRatio: 1.35 },
  },
  {
    id: "obj_person",
    targetClass: "person",
    family: "object",
    description: "User / Person Object",
    positiveDescription: "Circular head sitting atop triangular or curved shoulders body",
    hardNegatives: HARD_NEGATIVES_MAP["person"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2], minAspectRatio: 0.45, maxAspectRatio: 1.2 },
  },
  {
    id: "obj_car",
    targetClass: "car",
    family: "object",
    description: "Automobile / Car Object",
    positiveDescription: "Horizontal vehicle silhouette with roof cabin and two circular wheels at bottom",
    hardNegatives: HARD_NEGATIVES_MAP["car"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [3], minAspectRatio: 1.2, maxAspectRatio: 3.5 },
  },
  {
    id: "obj_clock",
    targetClass: "clock",
    family: "object",
    description: "Clock / Time Object",
    positiveDescription: "Circular outer dial enclosing perpendicular hour and minute hands",
    hardNegatives: HARD_NEGATIVES_MAP["clock"],
    priors: { minStrokes: 1, maxStrokes: 3, preferredStrokes: [2, 3], minAspectRatio: 0.75, maxAspectRatio: 1.33 },
  },
  {
    id: "obj_database",
    targetClass: "database",
    family: "object",
    description: "Database Object",
    positiveDescription: "Stacked vertical cylinder disks with curved elliptical lips",
    hardNegatives: HARD_NEGATIVES_MAP["database"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [1, 2], minAspectRatio: 0.45, maxAspectRatio: 1.2 },
  },
  {
    id: "obj_server",
    targetClass: "server",
    family: "object",
    description: "Server Rack Object",
    positiveDescription: "Stacked horizontal server rack modules with indicator status dots",
    hardNegatives: HARD_NEGATIVES_MAP["server"],
    priors: { minStrokes: 1, maxStrokes: 4, preferredStrokes: [2, 3], minAspectRatio: 0.5, maxAspectRatio: 1.8 },
  },
]

export const ALL_CLASS_DEFINITIONS: ClassDefinition[] = [
  ...LETTER_DEFINITIONS,
  ...DIGIT_DEFINITIONS,
  ...GEOMETRY_DEFINITIONS,
  ...OBJECT_DEFINITIONS,
]
