// ---------------------------------------------------------------------------
// Zenith AI — Model Registry & Provider Capabilities
// ---------------------------------------------------------------------------

import type { AIProviderId, AIProviderMeta, AIModelMeta } from "./types"

export const AI_PROVIDERS: Record<AIProviderId, AIProviderMeta> = {
  gemini: {
    id: "gemini",
    name: "Google Gemini",
    description: "State-of-the-art multimodal reasoning, ultra-fast response, and 2M token context window.",
    website: "https://ai.google.dev",
    requiresApiKey: true,
    models: [
      {
        id: "gemini-3.8-flash",
        name: "Gemini 3.8 Flash",
        providerId: "gemini",
        description: "Ultra-fast flagship model for general text, study copilot, and reasoning tasks.",
        contextWindow: 1048576,
        isDefault: true,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: true,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0.075, outputPerMillionUsd: 0.3 },
        recommendedFor: ["fast-solving", "flashcards", "mind-maps", "flowcharts", "pdf-analysis"],
      },
      {
        id: "gemini-3.7-flash",
        name: "Gemini 3.7 Flash",
        providerId: "gemini",
        description: "High-performance multimodal model with advanced STEM and hybrid reasoning.",
        contextWindow: 1048576,
        isDefault: false,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: true,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0.075, outputPerMillionUsd: 0.3 },
        recommendedFor: ["fast-solving", "flashcards", "mind-maps", "flowcharts", "pdf-analysis"],
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        providerId: "gemini",
        description: "Deep reasoning, high-precision STEM, code generation, and complex diagramming.",
        contextWindow: 2097152,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: true,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 1.25, outputPerMillionUsd: 5.0 },
        recommendedFor: ["deep-reasoning", "complex-math", "comprehensive-study-plans"],
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        providerId: "gemini",
        description: "Cost-efficient lightweight fallback model.",
        contextWindow: 1048576,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: true,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 0.075, outputPerMillionUsd: 0.3 },
      },
    ],
  },

  openai: {
    id: "openai",
    name: "OpenAI",
    description: "Industry-standard GPT-4o models and reasoning models (o1, o3-mini).",
    website: "https://platform.openai.com",
    requiresApiKey: true,
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        providerId: "openai",
        description: "Flagship versatile multimodal model.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 2.5, outputPerMillionUsd: 10.0 },
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o mini",
        providerId: "openai",
        description: "Affordable fast intelligence for everyday study tasks.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 0.15, outputPerMillionUsd: 0.6 },
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        providerId: "openai",
        description: "High-speed reasoning model specialized in math, science, and coding.",
        contextWindow: 200000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 1.1, outputPerMillionUsd: 4.4 },
      },
    ],
  },

  groq: {
    id: "groq",
    name: "Groq",
    description: "Ultra-fast low-latency inference powered by Groq LPU technology.",
    website: "https://groq.com",
    supportsCustomEndpoint: true,
    defaultEndpoint: "https://api.groq.com/openai/v1/chat/completions",
    requiresApiKey: true,
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        providerId: "groq",
        description: "Flagship 70B frontier open model on Groq LPU with 128K context.",
        contextWindow: 128000,
        isDefault: true,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0.59, outputPerMillionUsd: 0.79 },
        recommendedFor: ["diagram-generation", "step-by-step-learning", "fast-responses"],
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        providerId: "groq",
        description: "Ultra-high speed 8B model with sub-second time-to-first-token.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 0.05, outputPerMillionUsd: 0.08 },
        recommendedFor: ["quick-notes", "flashcards", "instant-feedback"],
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        providerId: "groq",
        description: "High-capacity open architecture model optimized on Groq.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0.8, outputPerMillionUsd: 1.2 },
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT-OSS 20B",
        providerId: "groq",
        description: "Balanced reasoning and generation efficiency on Groq LPU.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 0.2, outputPerMillionUsd: 0.4 },
      },
      {
        id: "qwen/qwen3.6-27b",
        name: "Qwen 3.6 27B",
        providerId: "groq",
        description: "High-performance multilingual and coding model on Groq.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0.35, outputPerMillionUsd: 0.7 },
      },
    ],
  },

  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    description: "Unified router access to 200+ models from Anthropic, OpenAI, Meta, DeepSeek, Google, and open weights.",
    website: "https://openrouter.ai",
    supportsCustomEndpoint: true,
    defaultEndpoint: "https://openrouter.ai/api/v1",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek/deepseek-r1:free",
        name: "DeepSeek R1 (Free)",
        providerId: "openrouter",
        description: "Frontier open-weights reasoning model with chain-of-thought verification.",
        contextWindow: 163840,
        isDefault: true,
        isFree: true,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0, outputPerMillionUsd: 0 },
        recommendedFor: ["free-tier", "deep-reasoning", "math-logic", "code-architect"],
      },
      {
        id: "meta-llama/llama-3.3-70b-instruct:free",
        name: "Llama 3.3 70B Instruct (Free)",
        providerId: "openrouter",
        description: "Meta's flagship 70B open model via high-speed free tier community routing.",
        contextWindow: 131072,
        isFree: true,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0, outputPerMillionUsd: 0 },
        recommendedFor: ["free-tier", "general-knowledge", "diagram-generation"],
      },
      {
        id: "google/gemini-2.0-flash-exp:free",
        name: "Gemini 2.0 Flash Exp (Free)",
        providerId: "openrouter",
        description: "Google multimodal speed & context window via OpenRouter free tier.",
        contextWindow: 1048576,
        isFree: true,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0, outputPerMillionUsd: 0 },
        recommendedFor: ["free-tier", "fast-chat", "multimodal"],
      },
      {
        id: "anthropic/claude-3.7-sonnet",
        name: "Claude 3.7 Sonnet (via OpenRouter)",
        providerId: "openrouter",
        description: "Hybrid reasoning and code architecture through OpenRouter.",
        contextWindow: 200000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 3.0, outputPerMillionUsd: 15.0 },
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o (via OpenRouter)",
        providerId: "openrouter",
        description: "OpenAI flagship omni model routed via OpenRouter.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 2.5, outputPerMillionUsd: 10.0 },
      },
    ],
  },

  anthropic: {
    id: "anthropic",
    name: "Anthropic Claude",
    description: "Claude 3.7 Sonnet & 3.5 Haiku with hybrid thinking and nuanced synthesis.",
    website: "https://anthropic.com",
    requiresApiKey: true,
    models: [
      {
        id: "claude-3-7-sonnet-20250219",
        name: "Claude 3.7 Sonnet",
        providerId: "anthropic",
        description: "Hybrid reasoning model capable of standard chat and extended thinking.",
        contextWindow: 200000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 3.0, outputPerMillionUsd: 15.0 },
      },
      {
        id: "claude-3-5-haiku-20241022",
        name: "Claude 3.5 Haiku",
        providerId: "anthropic",
        description: "Sub-second responsiveness for flashcards, notes, and quick summaries.",
        contextWindow: 200000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 0.8, outputPerMillionUsd: 4.0 },
      },
    ],
  },

  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    description: "Open-weights reasoning (R1) and general chat (V3) at disruptive cost.",
    website: "https://platform.deepseek.com",
    requiresApiKey: true,
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek-V3",
        providerId: "deepseek",
        description: "High-capability general assistant with 64K context.",
        contextWindow: 64000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 0.14, outputPerMillionUsd: 0.28 },
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek-R1",
        providerId: "deepseek",
        description: "Open reasoning model with chain-of-thought verification.",
        contextWindow: 64000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: false,
          documentInput: false,
          webSearch: false,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 0.55, outputPerMillionUsd: 2.19 },
      },
    ],
  },

  perplexity: {
    id: "perplexity",
    name: "Perplexity",
    description: "Online search-augmented reasoning with live academic & web citations.",
    website: "https://perplexity.ai",
    requiresApiKey: true,
    models: [
      {
        id: "sonar",
        name: "Sonar Online",
        providerId: "perplexity",
        description: "Real-time web search and grounded factual synthesis.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: false,
          documentInput: false,
          webSearch: true,
          reasoning: false,
        },
        pricing: { inputPerMillionUsd: 1.0, outputPerMillionUsd: 1.0 },
      },
      {
        id: "sonar-reasoning",
        name: "Sonar Reasoning",
        providerId: "perplexity",
        description: "Search-grounded deep reasoning for research papers and literature reviews.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: false,
          documentInput: false,
          webSearch: true,
          reasoning: true,
        },
        pricing: { inputPerMillionUsd: 1.0, outputPerMillionUsd: 5.0 },
      },
    ],
  },

  huggingface: {
    id: "huggingface",
    name: "Hugging Face Inference",
    description: "Serverless inference for open models (Llama 3.3, Qwen 2.5).",
    website: "https://huggingface.co",
    requiresApiKey: true,
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B",
        providerId: "huggingface",
        description: "Open frontier model for knowledge and multi-step reasoning.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: true,
          documentInput: false,
          webSearch: false,
          reasoning: false,
        },
      },
    ],
  },

  azure: {
    id: "azure",
    name: "Microsoft Azure Foundry",
    description: "Enterprise OpenAI & Mistral deployments hosted on your Azure tenant.",
    website: "https://azure.microsoft.com",
    supportsCustomEndpoint: true,
    requiresApiKey: true,
    models: [
      {
        id: "gpt-4o",
        name: "Azure GPT-4o",
        providerId: "azure",
        description: "Enterprise-hosted GPT-4o with tenant isolation.",
        contextWindow: 128000,
        capabilities: {
          chat: true,
          streaming: true,
          vision: true,
          structuredOutput: true,
          tools: true,
          documentInput: true,
          webSearch: false,
          reasoning: true,
        },
      },
    ],
  },

  "openai-compatible": {
    id: "openai-compatible",
    name: "OpenAI Compatible / Self-Hosted",
    description: "Connect to Ollama, vLLM, LMStudio, LocalAI, or any custom API gateway.",
    website: "https://ollama.ai",
    supportsCustomEndpoint: true,
    defaultEndpoint: "http://localhost:11434/v1",
    requiresApiKey: false,
    models: [
      {
        id: "custom-model",
        name: "Custom / Local Model",
        providerId: "openai-compatible",
        description: "Configured via custom endpoint URL.",
        contextWindow: 32768,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: false,
          documentInput: false,
          webSearch: false,
          reasoning: false,
        },
      },
    ],
  },

  custom: {
    id: "custom",
    name: "Custom Enterprise Gateway",
    description: "Custom internal AI proxy with bearer token authorization.",
    website: "https://zenithsui.internal",
    supportsCustomEndpoint: true,
    requiresApiKey: true,
    models: [
      {
        id: "enterprise-default",
        name: "Enterprise Default Model",
        providerId: "custom",
        description: "Enterprise routed gateway.",
        contextWindow: 65536,
        capabilities: {
          chat: true,
          streaming: true,
          vision: false,
          structuredOutput: true,
          tools: false,
          documentInput: false,
          webSearch: false,
          reasoning: false,
        },
      },
    ],
  },
}

export function getModelMeta(providerId: AIProviderId, modelId: string): AIModelMeta {
  const provider = AI_PROVIDERS[providerId]
  if (!provider) {
    return AI_PROVIDERS.gemini.models[0]
  }
  const match = provider.models.find((m) => m.id === modelId)
  return match || provider.models[0] || AI_PROVIDERS.gemini.models[0]
}

export function getAllModels(): AIModelMeta[] {
  const list: AIModelMeta[] = []
  for (const provider of Object.values(AI_PROVIDERS)) {
    list.push(...provider.models)
  }
  return list
}
