// Generates lib/sketch/phosphor-paths.ts from @phosphor-icons/core regular SVGs.
// Run: node scripts/gen-icons.mjs

import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const assets = join(root, "node_modules/@phosphor-icons/core/assets/regular")

const NAMES = `
user users user-circle user-plus image images magnifying-glass
caret-down caret-right caret-left caret-up caret-up-down check check-circle
x x-circle plus minus list star heart arrow-right arrow-left arrow-up arrow-down
arrow-u-up-left arrow-square-out dots-three dots-three-vertical dots-six-vertical
bell bell-ringing gear house envelope lock lock-open trash upload-simple
download-simple calendar-blank calendar-check info warning warning-circle play
pause squares-four file file-text folder chart-line chart-bar chart-pie
shopping-cart shopping-bag credit-card currency-dollar tag bookmark bookmark-simple
chat-circle chat-teardrop-dots chats-circle paper-plane-tilt sparkle robot
lightning globe link share-network copy pencil-simple pencil-line funnel funnel-simple
sliders-horizontal sort-ascending clock map-pin phone video-camera microphone
paperclip database code terminal browser device-mobile desktop sign-out sign-in
eye eye-slash thumbs-up thumbs-down smiley question shield-check rocket-launch
package truck gift trophy medal fire moon sun palette note notepad kanban
graduation-cap buildings briefcase wallet receipt bank arrows-clockwise
arrows-out arrows-in magic-wand brain cpu plug wrench bug git-branch git-pull-request
cloud cloud-arrow-up wifi-high battery-full camera crop text-aa text-b
list-bullets list-numbers list-checks text-align-left table columns rows
sidebar-simple playlist quotes megaphone hand-waving crown seal-check
lightbulb target flag confetti coins percent hash at squares-four
dot-outline circle square triangle diamond hourglass timer bookmarks
airplane-tilt storefront ticket key fingerprint scan qr-code
`.trim().split(/\s+/)

const out = {}
const missing = []
for (const name of [...new Set(NAMES)]) {
  const file = join(assets, `${name}.svg`)
  if (!existsSync(file)) {
    missing.push(name)
    continue
  }
  const svg = readFileSync(file, "utf8")
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1])
  if (!ds.length) {
    missing.push(name)
    continue
  }
  out[name] = ds
}

const body = Object.entries(out)
  .map(([k, v]) => `  ${JSON.stringify(k)}: [${v.map((d) => JSON.stringify(d)).join(", ")}],`)
  .join("\n")

writeFileSync(
  join(root, "lib/sketch/phosphor-paths.ts"),
  `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n` +
    `// Phosphor "regular" icons, filled paths in a 0 0 256 256 viewBox.\n\n` +
    `export const PHOSPHOR_VB = 256\n\n` +
    `export const PHOSPHOR_PATHS: Record<string, string[]> = {\n${body}\n}\n`
)

console.log(`wrote ${Object.keys(out).length} icons`)
if (missing.length) console.log(`missing (skipped): ${missing.join(" ")}`)
